const appData = {
    navigators: [
        {
            name: "Socrates",
            lifespan: "470-399 BC",
            title: "The Questioning Philosopher",
            summary: "Defined identity around the relentless pursuit of truth and virtue, challenging societal norms through rigorous questioning.",
            bioLink: "https://www.britannica.com/biography/Socrates",
            videoUrl: null,
            identityKernel: "His identity was defined by the relentless pursuit of truth and virtue. His famous declaration, 'the unexamined life is not worth living,' placed philosophical inquiry and moral integrity above social conformity, guiding his every decision.",
            prf: "Living in democratic Athens, his Personal Reality Framework included a civic duty to question authority and tradition. He saw this Socratic questioning not as subversion, but as a necessary act to achieve genuine justice and virtue within his society.",
            futurePull_RMB: "Socrates acted from a deep sense of personal conscience and civic duty. He engaged with the legal system but refused to betray his principles, envisioning a future where truth and reason would be the ultimate arbiters, thereby shaping the entire course of Western ethics.",
            atcf: "He maintained perfect temporal consistency from his public teaching to his trial and death. By choosing execution over exile or silence, he created an unwavering narrative of integrity, demonstrating that his core values were more important than his own survival.",
            dramaticExample: "His calm acceptance of the death sentence by hemlock. He refused multiple opportunities to flee Athens, arguing that to do so would betray his lifelong commitment to the laws of the city and the principles of justice he had always taught.",
            capabilities: ["Capability for Public Reasoning", "Capability for Principled Dissent", "Capability for Maintaining Coherence Under Duress"],
            relatedChapters: [{ chapter: "1", topic: "Ethics Begins Where You Are" }, { chapter: "4", topic: "Reasoning in an Ethical World" }, { chapter: "14", topic: "Ethics Across Time and Legacy" }]
        },
        {
            name: "Harriet Tubman",
            lifespan: "c.1820–1913",
            title: "The Liberator",
            summary: "An escaped slave who became a leading abolitionist, guiding dozens to freedom on the Underground Railroad.",
            bioLink: "https://www.britannica.com/biography/Harriet-Tubman",
            videoUrl: null,
            identityKernel: "A steadfast belief in freedom, human dignity, and divine justice. Known as 'Moses of her people,' her core value was that all people deserve liberty, famously expressed in her resolve to 'be free or die.'",
            prf: "Her framework was forged in the brutal context of American slavery. Guided by deep faith, she navigated a world of slave-catching laws and violent opposition by relying on a secret network of abolitionist allies and safe houses.",
            futurePull_RMB: "She used every available tool—disguises, coded songs, and strategic timing—to manifest a future of freedom for others. Her actions were pulled by the vision of a world without slavery, and she never lost a fugitive under her charge.",
            atcf: "A perfectly coherent narrative of liberation. After freeing herself, she returned to the South approximately 13 times to rescue around 70 others. She continued this mission as a Union scout during the Civil War and later as an advocate for women's suffrage.",
            dramaticExample: "Leading the Combahee Ferry Raid during the Civil War. This armed military operation, which she helped plan and guide, successfully liberated more than 750 enslaved people, making her the first woman to lead such an expedition in U.S. history.",
            capabilities: ["Capability for Covert Action and Resistance", "Capability for Building Trust Networks", "Capability for Moral Courage in the Face of Extreme Risk"],
            relatedChapters: [{ chapter: "5", topic: "Agents in Ethical Systems" }, { chapter: "7", topic: "Justice and Fairness" }, { chapter: "13", topic: "Political Responsibility & Collective Action" }]
        },
        {
            name: "Mahatma Gandhi",
            lifespan: "1869–1948",
            title: "The Nonviolent Leader",
            summary: "Led India to independence from British rule through nonviolent civil disobedience.",
            bioLink: "https://www.britannica.com/biography/Mahatma-Gandhi",
            videoUrl: null,
            identityKernel: "Built on 'satyagraha' (truth-force) and 'ahimsa' (nonviolence). He believed that ethical ends must be achieved by ethical means, making nonviolent action a core principle, not just a tactic.",
            prf: "His framework was shaped by colonial oppression in South Africa and British India. He combined his Hindu-Jain spiritual upbringing with a legal education to innovate new forms of resistance against a powerful empire.",
            futurePull_RMB: "Gandhi's actions were pulled by a future vision of a free and harmonious India. He believed that the means used in the struggle would shape the future society, so he insisted on nonviolence to create a foundation for a peaceful nation.",
            atcf: "A consistent narrative of principled resistance. From his early work in South Africa to leading the Salt March and fasting to quell violence, the thread of nonviolence runs unbroken. He never wavered, even in the face of brutal crackdowns.",
            dramaticExample: "The 1930 Salt March, a 240-mile march to the sea to protest the British salt tax. This act of mass civil disobedience was a simple, powerful, and nonviolent challenge to the authority of the British Empire, inspiring millions.",
            capabilities: ["Capability for Strategic Nonviolent Action", "Capability for Mass Mobilization", "Capability for Integrating Spiritual and Political Life"],
            relatedChapters: [{ chapter: "2", topic: "Navigating Ethical Terrain" }, { chapter: "13", topic: "Protest, Dissent, and Disruption" }, { chapter: "14", topic: "Ethics Across Time and Legacy" }]
        },
        {
            name: "Dorothy Day",
            lifespan: "1897–1980",
            title: "The Compassionate Anarchist",
            summary: "Co-founded the Catholic Worker Movement, combining direct aid for the poor with nonviolent social activism.",
            bioLink: "https://www.britannica.com/biography/Dorothy-Day",
            videoUrl: null,
            identityKernel: "A fusion of Catholic faith and radical social justice. Her core values were voluntary poverty, nonviolence, and a profound belief in the dignity of every person, especially the marginalized.",
            prf: "Operating during the Great Depression, WWII, and the Cold War, her framework was a world of economic despair and war. She created the Catholic Worker Movement as a 'third way' between capitalist greed and communist atheism.",
            futurePull_RMB: "Her actions were guided by the Christian vision of the Kingdom of God on Earth. She built 'houses of hospitality' and farmed communes as present-day models of the compassionate, just society she believed was possible in the future.",
            atcf: "After her conversion to Catholicism, she sustained a consistent path of 'compassionate anarchism' for nearly 50 years. From sheltering the homeless in the 1930s to being jailed for protesting war at age 75, her commitment to the poor and to pacifism never wavered.",
            dramaticExample: "Maintaining her pacifist stance during World War II, a deeply unpopular and isolating position. Her newspaper, The Catholic Worker, refused to support the war, leading to a massive loss of subscribers but demonstrating her unwavering commitment to nonviolence.",
            capabilities: ["Capability for Direct Action and Mutual Aid", "Capability for Prophetic Witness", "Capability for Living in Solidarity with the Poor"],
            relatedChapters: [{ chapter: "6", topic: "Human Development & Ethical Formation" }, { chapter: "10", topic: "Economic Systems & Value" }, { chapter: "12", topic: "Health, Healing, & Ethics of Care" }]
        },
        {
            name: "Sophie Scholl",
            lifespan: "1921-1943",
            title: "The Conscientious Resister",
            summary: "A member of the White Rose non-violent resistance group in Nazi Germany, executed for distributing anti-war leaflets.",
            bioLink: "https://www.britannica.com/biography/Sophie-Scholl",
            videoUrl: null,
            identityKernel: "A principled conscience and profound moral courage. Raised in a Christian family opposed to Nazism, she believed ordinary citizens had a duty to speak out against evil and protect human dignity.",
            prf: "Her reality was the oppressive Nazi regime during WWII. After an initial period in the Hitler Youth, she experienced a profound dissonance between Nazi propaganda and her Christian ethics, which awakened her resistance.",
            futurePull_RMB: "She acted with the hope of a future Germany free from tyranny. The White Rose leaflets were not just a protest but an attempt to awaken the conscience of other Germans to build a different, more humane future.",
            atcf: "Though her life was short, her narrative is a dramatic arc of ethical awakening and steadfastness. She transformed from a compliant youth into an anti-Nazi martyr, fulfilling her core values of truth and justice even at the cost of her life.",
            dramaticExample: "Her calm defiance during her trial for treason. When caught distributing leaflets, she refused to recant her beliefs, telling the judge, 'Somebody, after all, had to make a start.' She was executed by guillotine just hours later.",
            capabilities: ["Capability for Youth Activism and Dissent", "Capability for Articulating Moral Conscience", "Capability for Ultimate Sacrifice for Principle"],
            relatedChapters: [{ chapter: "4", topic: "Reasoning in an Ethical World" }, { chapter: "5", topic: "Agents in Ethical Systems" }, { chapter: "13", topic: "Protest, Dissent, and Disruption" }]
        },
        {
            name: "Oskar Schindler",
            lifespan: "1908–1974",
            title: "The Unlikely Savior",
            summary: "A German industrialist and Nazi Party member who saved over 1,000 Jews during the Holocaust by employing them in his factories.",
            bioLink: "https://encyclopedia.ushmm.org/content/en/article/oskar-schindler",
            videoUrl: null,
            identityKernel: "Evolved from a greedy opportunist to a courageous protector, valuing human life over profit and ideology. His self-concept underwent a profound transformation driven by his conscience.",
            prf: "Operated within the genocidal machinery of Nazi Germany, using his position as a factory owner with Nazi contacts to first exploit, and later, to save Jewish workers from the Holocaust.",
            futurePull_RMB: "He leveraged his context (money, charm, connections) to subvert Nazi aims, driven by a dawning conscience and the imagined remorse of inaction. His actions were pulled by the desire to save the lives he saw before him.",
            atcf: "A dramatic two-act narrative showing profound ethical transformation. He spent his entire fortune to rescue over 1,000 Jews, demonstrating a complete realignment of his values from self-interest to altruism.",
            dramaticExample: "Creating 'Schindler's list' to transfer about 1,200 Jewish prisoners from the Płaszów concentration camp to the relative safety of his new factory in Brünnlitz, an act that required immense bribery and personal risk.",
            capabilities: ["Capability for Ethical Transformation", "Capability for Using Systemic Levers for Moral Ends", "Capability for Risking All for Human Life"],
            relatedChapters: [{ chapter: "6", topic: "Identity, Trauma, and Ethical Disruption" }, { chapter: "5", topic: "Agents in Ethical Systems" }, { chapter: "10", topic: "Economic Systems & Value" }]
        },
        {
            name: "Martin Luther King Jr.",
            lifespan: "1929–1968",
            title: "The Dreamer of Justice",
            summary: "A pivotal leader in the American Civil Rights Movement, advocating for racial equality through nonviolent protest.",
            bioLink: "https://www.britannica.com/biography/Martin-Luther-King-Jr",
            videoUrl: null,
            identityKernel: "Grounded in Christian love, justice, and nonviolent activism; saw civil rights as a moral and spiritual mission. He believed in the equal dignity of all people and nonviolence as 'a way of life for courageous people.'",
            prf: "Fought against entrenched Jim Crow segregation in the American South, leveraging Black churches as organizing hubs and media to expose brutality and awaken the nation's conscience.",
            futurePull_RMB: "Guided by the vision of a 'Beloved Community' and a future of racial harmony, as powerfully articulated in his 'I Have a Dream' speech. This vision of a just future shaped his strategy of nonviolent resistance.",
            atcf: "An expanding impact grounded in consistent values. From the Montgomery Bus Boycott to the Poor People's Campaign, he always adhered to nonviolence, even as he broadened his focus to include economic justice and anti-war activism.",
            dramaticExample: "Writing the 'Letter from Birmingham Jail,' where he articulated the moral duty to disobey unjust laws. This act turned his imprisonment into a powerful platform for the movement's ethical framework, responding directly to criticism from his context.",
            capabilities: ["Capability for Oratorical Moral Persuasion", "Capability for Coalition Building Across Divides", "Capability for Strategic Nonviolent Confrontation"],
            relatedChapters: [{ chapter: "7", topic: "Justice and the Architecture of Fairness" }, { chapter: "13", topic: "Political Responsibility & Collective Action" }, { chapter: "14", topic: "Ethics Across Time and Legacy" }]
        },
        {
            name: "Malcolm X",
            lifespan: "1925–1965",
            title: "The Evolving Revolutionary",
            summary: "An influential African American leader who advocated for Black empowerment, evolving from separatism to a more inclusive human rights vision.",
            bioLink: "https://www.britannica.com/biography/Malcolm-X",
            videoUrl: null,
            identityKernel: "Marked by an evolution from advocating Black nationalism and self-defense 'by any means necessary' to a more inclusive vision of human rights, with integrity and courage as constants throughout.",
            prf: "Shaped by personal trauma (his father's murder) and systemic racism. The Nation of Islam provided an initial framework, which he later outgrew after his pilgrimage to Mecca exposed him to a different reality of racial unity.",
            futurePull_RMB: "Initially pulled by a future of Black self-sufficiency and separation. Later, after his Hajj, he was pulled by a new vision of racial brotherhood and global human rights, which he worked to build in his final year.",
            atcf: "A narrative of profound transformation, coherently explained by his own public acknowledgment of his growth. He maintained a consistent drive for justice and truth, even as his specific beliefs evolved dramatically.",
            dramaticExample: "His pilgrimage to Mecca in 1964, which radically changed his views on race and Islam. He returned to the US and publicly renounced the Nation of Islam's separatist doctrines, an act of intellectual honesty that put his life at great risk.",
            capabilities: ["Capability for Self-Transformation and Public Revision", "Capability for Articulating Oppressed Voices", "Capability for Intellectual Honesty"],
            relatedChapters: [{ chapter: "3", topic: "Ethical Perception in a Filtered World" }, { chapter: "6", topic: "Identity, Trauma, and Ethical Disruption" }, { chapter: "13", topic: "Citizenship, Identity, and Belonging" }]
        },
        {
            name: "Nelson Mandela",
            lifespan: "1918–2013",
            title: "The Architect of Reconciliation",
            summary: "A South African anti-apartheid revolutionary who became the country's first Black president, leading a transition to a multiracial democracy.",
            bioLink: "https://www.britannica.com/biography/Nelson-Mandela",
            videoUrl: null,
            identityKernel: "An unshakeable commitment to justice, equality, and reconciliation. Famously stated at his trial that a democratic and free society was an ideal 'for which I am prepared to die.'",
            prf: "Fought against the oppressive system of apartheid. His context shifted from nonviolent protest to armed resistance (targeting infrastructure) after the Sharpeville Massacre, and then to 27 years of imprisonment.",
            futurePull_RMB: "Guided by the vision of a future 'Rainbow Nation.' He studied the language and culture of his oppressors while in prison to prepare for future negotiations and reconciliation, acting in the present for the future he envisioned.",
            atcf: "A consistent narrative from activist to prisoner to president. He emerged from prison not with bitterness, but with a focus on forgiveness, establishing the Truth and Reconciliation Commission instead of seeking retribution.",
            dramaticExample: "Donning the Springbok rugby jersey—a symbol of white Afrikaner pride—at the 1995 Rugby World Cup final. This single gesture became a powerful symbol of his commitment to national unity and reconciliation over vengeance.",
            capabilities: ["Capability for Forgiveness and Reconciliation", "Capability for Long-Term Strategic Patience", "Capability for Holding Contradictory Roles (Freedom Fighter and Peacemaker)"],
            relatedChapters: [{ chapter: "7", topic: "Justice and the Architecture of Fairness" }, { chapter: "13", topic: "Building Political Coherence" }, { chapter: "14", topic: "Ethics Across Time and Legacy" }]
        },
        {
            name: "Rachel Carson",
            lifespan: "1907–1964",
            title: "The Ecological Conscience",
            summary: "A marine biologist and author whose book 'Silent Spring' is credited with advancing the global environmental movement.",
            bioLink: "https://www.britannica.com/biography/Rachel-Carson",
            videoUrl: null,
            identityKernel: "A sense of wonder for the natural world and a moral conviction to protect it through scientific truth-telling. An identity as a responsible citizen-scientist who must alert society to danger.",
            prf: "Operated in a post-WWII American culture that celebrated chemical pesticides like DDT as miracles of science. As a woman scientist, she faced gendered attacks from the powerful chemical industry meant to discredit her as 'hysterical.'",
            futurePull_RMB: "Her work was driven by the imagined future of a 'silent spring' where birds and wildlife were decimated by pesticides. This vision of potential catastrophe motivated her urgent action in the present.",
            atcf: "A narrative of awakening to an ethical calling. She evolved from a nature writer to a reluctant but steadfast advocate, consistently acting out of care for living creatures, even while battling the cancer that would take her life.",
            dramaticExample: "Publishing *Silent Spring* in 1962 despite a massive smear campaign from the powerful chemical industry. Her meticulous research and clear, eloquent prose successfully awakened the public and led to major environmental reforms.",
            capabilities: ["Capability for Translating Science into Public Moral Action", "Capability for Resisting Corporate Disinformation", "Capability for Ecological Empathy"],
            relatedChapters: [{ chapter: "8", topic: "Technological Frontiers" }, { chapter: "9", topic: "Environmental Cartography" }, { chapter: "5", topic: "Agents in Ethical Systems" }]
        },
        {
            name: "Jonas Salk",
            lifespan: "1914–1995",
            title: "The Humanitarian Scientist",
            summary: "Developed the first successful polio vaccine and famously refused to patent it, viewing it as a gift to humanity.",
            bioLink: "https://www.britannica.com/biography/Jonas-Salk",
            videoUrl: null,
            identityKernel: "Grounded in humanitarianism and scientific benevolence. His core value was to alleviate human suffering, viewing his work as a public good rather than a source of personal profit.",
            prf: "Worked during terrifying polio epidemics with massive public support from the March of Dimes. This shaped his view that the resulting vaccine was already 'owned' by the people who funded the research.",
            futurePull_RMB: "Guided by a future where polio was eradicated and life-saving science was accessible to all. He acted to maximize the global distribution of the vaccine, ensuring it reached the most people possible.",
            atcf: "A consistent narrative of scientific morality. From his early research to founding the Salk Institute, he demonstrated an ethos of open, human-centered science, always prioritizing public health over personal gain.",
            dramaticExample: "When asked by journalist Edward R. Murrow who owned the patent to the polio vaccine, he famously replied, 'Well, the people, I would say. There is no patent. Could you patent the sun?' This decision forfeited billions in potential personal wealth.",
            capabilities: ["Capability for Scientific Altruism", "Capability for Public Trust Building", "Capability for Redefining the Value of an Invention"],
            relatedChapters: [{ chapter: "8", topic: "Ethical Design and Hidden Values" }, { chapter: "10", topic: "Rethinking Value" }, { chapter: "12", topic: "The Moral Terrain of Health and Healing" }]
        },
        {
            name: "Ai Weiwei",
            lifespan: "b. 1957",
            title: "The Dissident Artist",
            summary: "A Chinese contemporary artist and activist who uses his work to critique authoritarianism and advocate for human rights.",
            bioLink: "https://www.britannica.com/biography/Ai-Weiwei",
            videoUrl: null,
            identityKernel: "An unflinching commitment to freedom of expression, truth, and justice. He sees creativity and dissent as inseparable acts of human dignity and challenges power without fear.",
            prf: "Shaped by his family's persecution under Mao and his exposure to Western ideas. He operates against the backdrop of an authoritarian Chinese state that censors dissent and punishes critics with imprisonment and violence.",
            futurePull_RMB: "Envisions a future China that respects human rights and free expression. This vision fuels his present-day activism and art, regardless of the severe personal cost, as he works to create a more open society.",
            atcf: "A consistent narrative of creative resistance. From his early art to his global advocacy, he has unwaveringly used his platform to speak truth to power, even after being beaten, detained for 81 days, and surveilled.",
            dramaticExample: "After his secret detention in 2011, he created the work 'S.A.C.R.E.D.,' a series of dioramas depicting his imprisonment. This act turned his personal trauma into a public witness against the state's abuses, refusing to be silenced.",
            capabilities: ["Capability for Artistic Dissent", "Capability for Using Technology for Transparency", "Capability for Enduring State Repression"],
            relatedChapters: [{ chapter: "5", topic: "Agents in Ethical Systems" }, { chapter: "13", topic: "Protest, Dissent, and Disruption" }, { chapter: "8", topic: "Technologies That Shape Us" }]
        },
        {
            name: "The 14th Dalai Lama",
            lifespan: "b. 1935",
            title: "The Compassionate Leader",
            summary: "The spiritual leader of Tibetan Buddhism, advocating for nonviolence, compassion, and interfaith harmony while in exile.",
            bioLink: "https://www.dalailama.com/the-dalai-lama/biography-and-daily-life/brief-biography",
            videoUrl: null,
            identityKernel: "A compassionate servant of peace, embodying Buddhist values of nonviolence (ahimsa), humility, and universal responsibility. He consistently refers to himself as 'a simple monk.'",
            prf: "Thrust into the role of head of state of Tibet during the Chinese invasion. He has spent over 60 years in exile, leading his people while navigating a complex international diplomatic arena and constant pressure from Beijing.",
            futurePull_RMB: "Guided by a vision of a peaceful, autonomous Tibet and a more compassionate world. His 'Middle Way' approach seeks a mutually beneficial solution for the future rather than total independence or continued conflict.",
            atcf: "A narrative of steadfast spiritual leadership through immense upheaval. He has consistently advocated for nonviolence and compassion, even when it was unpopular, and democratized his own government in exile.",
            dramaticExample: "Voluntarily relinquishing his political authority over the Tibetan government-in-exile in 2011 to empower a democratically elected leader. This act demonstrated his commitment to democratic principles over personal power.",
            capabilities: ["Capability for Compassion Towards Adversaries", "Capability for Spiritual Leadership in Exile", "Capability for Bridging Spiritual and Secular Ethics"],
            relatedChapters: [{ chapter: "2", topic: "Navigating Ethical Terrain" }, { chapter: "6", topic: "Culture, Context, and Life Scripts" }, { chapter: "13", topic: "Political Responsibility" }]
        },
        {
            name: "Malala Yousafzai",
            lifespan: "b. 1997",
            title: "The Fearless Advocate",
            summary: "A Pakistani activist for female education and the youngest Nobel Prize laureate, who survived an assassination attempt by the Taliban.",
            bioLink: "https://www.britannica.com/biography/Malala-Yousafzai",
            videoUrl: null,
            identityKernel: "A firm belief in the right to education for all girls, defined by bravery, optimism, and compassion. Her motto is 'One child, one teacher, one book, one pen can change the world.'",
            prf: "Grew up in Pakistan's Swat Valley under the Taliban, who banned girls from school. Her father, an educator, encouraged her to speak out against this injustice from a young age, creating a context of both oppression and support.",
            futurePull_RMB: "Driven by a vision of a future where all girls can go to school and achieve their potential. This vision fueled her activism even after she was targeted for assassination, pulling her toward a global advocacy role.",
            atcf: "A heroic narrative of resilience. The attempt on her life did not silence her but amplified her voice, transforming her personal trauma into a global movement for education. She consistently advocates for peace and education, not revenge.",
            dramaticExample: "Her speech at the United Nations on her 16th birthday, just nine months after being shot. She declared, 'They thought that the bullets would silence us, but they failed... Weakness, fear and hopelessness died. Strength, power and courage was born.'",
            capabilities: ["Capability for Youth Advocacy on a Global Stage", "Capability for Transforming Trauma into Action", "Capability for Unwavering Optimism"],
            relatedChapters: [{ chapter: "1", topic: "Ethics Begins Where You Are" }, { chapter: "11", topic: "Educational Expeditions" }, { chapter: "6", topic: "Identity, Trauma, and Disruption" }]
        }
    ],
    thinkers: [
        {
            name: "Confucius",
            lifespan: "551-479 BCE",
            title: "The Relational Sage",
            summary: "His PRF emerged from social upheaval, emphasizing relational wisdom and cultural cultivation as the foundation for social harmony.",
            assemblyHistory: "Born into minor nobility during a period of institutional decline, his framework was shaped by a deep reverence for traditional Zhou dynasty rituals and a practical need to address social disorder. His roles as an administrator, teacher, and wandering advisor integrated theoretical wisdom with the practical challenges of governance and moral education.",
            broa: "His BROA+ is centered on relational moral cultivation. Beliefs: Human beings develop through reciprocal care and fulfilling their social roles. Rules: Act with ritual propriety (Li) and benevolent governance (Ren). Ontology: Personhood is constituted through a network of social relationships, not an individual essence. Authenticity: Achieved through the sincere and excellent fulfillment of one's social duties.",
            atcf: "Confucius maintained remarkable coherence by adapting ancient cultural wisdom to contemporary social challenges. He integrated his roles as a scholar, teacher, and political advisor, always aiming to create a framework for social harmony that future generations could inherit and build upon.",
            fop: "His Future-Oriented Projections were focused on creating a durable educational and cultural legacy. He developed systematic approaches to moral education and reinterpreted classical traditions to ensure they would remain relevant for restoring social order and guiding future cultural development.",
            capabilities: ["Capability for Cultural Transmission and Reinterpretation", "Capability for Relational Moral Cultivation", "Capability for Integrating Theory and Governance"],
            videoUrl: null,
        },
        {
            name: "Aristotle",
            lifespan: "384-322 BCE",
            title: "The Systematic Thinker",
            summary: "Synthesized empirical observation with systematic logic to create a comprehensive framework for understanding ethics, politics, and the natural world.",
            assemblyHistory: "His father was a court physician, instilling an early respect for empirical observation. This was combined with twenty years of training in abstract reasoning at Plato's Academy. This unique blend created a tension that fueled his life's work: grounding philosophical ideals in the observable, practical world.",
            broa: "BROA+ is grounded in an empirical and teleological worldview. Beliefs: Knowledge begins with sensory experience, and everything in nature has a purpose (telos). Rules: Virtue is a 'golden mean' between extremes, and valid conclusions come from integrating inductive observation with deductive logic. Ontology: Reality consists of individual substances with essential properties. Authenticity: Achieved through a life that harmonizes intellectual development, ethical character, and political engagement to achieve 'eudaimonia' (flourishing).",
            atcf: "Aristotle consistently integrated his multiple roles as a philosopher, scientist, tutor to Alexander the Great, and founder of his own school, the Lyceum. He adapted Plato's methods but maintained his core commitment to empirical investigation, demonstrating a coherent evolution of thought.",
            fop: "He aimed to create a permanent legacy of systematic knowledge. He organized human understanding into distinct disciplines (logic, physics, ethics) and created a research institution (the Lyceum) designed to continue this work for future generations.",
            capabilities: ["Capability for Systematic Categorization", "Capability for Integrating Empirical and Rational Methods", "Capability for Institutionalizing Knowledge"],
            videoUrl: null,
        },
        {
            name: "Marcus Aurelius",
            lifespan: "121-180 CE",
            title: "The Philosopher Emperor",
            summary: "A Roman Emperor who used Stoic philosophy to navigate the immense pressures of power, war, and personal loss, documenting his struggle for inner coherence in his private Meditations.",
            assemblyHistory: "Born into Roman aristocracy and groomed for power from a young age, he was also deeply immersed in Stoic philosophy. His entire life was a balancing act between the absolute external power of an emperor and the Stoic belief that true good comes only from inner virtue and rational self-control.",
            broa: "His BROA+ is a practical application of Stoicism. Beliefs: The universe is rationally ordered (Logos), and virtue is the only true good. Rules: Begin each day preparing for difficult people; focus only on the present moment; approach others with sympathetic understanding. Ontology: The self is a rational agent participating in a larger cosmic order; death is a natural transformation. Authenticity: Aligning one's inner philosophical commitments with the duties of one's external role, no matter how difficult.",
            atcf: "His Meditations serve as a real-time record of his effort to maintain temporal coherence. Despite plagues, constant warfare on the frontier, and personal betrayals, he consistently returned to his Stoic principles, using his writing to process events and reinforce his identity as a philosopher-emperor.",
            fop: "Aurelius was acutely aware of his legacy. His projections were focused on governing justly, establishing stable precedents for the empire, and providing a personal example of how philosophy can be a practical guide for living a virtuous life even under extreme pressure.",
            capabilities: ["Capability for Self-Examination Under Pressure", "Capability for Integrating Philosophical and Political Roles", "Capability for Maintaining Rational Composure in Crisis"],
            videoUrl: null,
        },
        {
            name: "Augustine of Hippo",
            lifespan: "354-430 CE",
            title: "The Radical Transformer",
            summary: "A theologian and philosopher whose radical personal conversion and intellectual synthesis of classical and Christian thought shaped Western Christianity.",
            assemblyHistory: "Born in Roman North Africa to a pagan father and a devout Christian mother (Monica), his youth was marked by ambition, classical education, and a decade-long adherence to Manichaeism. A profound personal and intellectual crisis led to his famous conversion to Christianity, mediated by Neoplatonic philosophy and the preaching of Ambrose of Milan.",
            broa: "His post-conversion BROA+ is built on the integration of faith and reason. Beliefs: God creates from nothing; evil is the privation of good; salvation comes through divine grace. Rules: Scripture holds ultimate authority, interpreted through philosophical wisdom; authentic Christian life is communal and pastoral. Ontology: A hierarchical creation where all is good, but human will is disordered. Authenticity: 'Faith seeking understanding,' where personal spiritual development must serve the broader community.",
            atcf: "His Confessions is a masterwork of temporal coherence analysis. He successfully integrated his past self (the ambitious rhetorician) with his present self (the Bishop of Hippo) into a coherent narrative of divine grace, preserving his intellectual skills while fundamentally reorienting their purpose.",
            fop: "He projected a future defined by the 'City of God' versus the 'City of Man.' His theological work was designed to provide a durable intellectual and spiritual framework for the Church to navigate the collapse of the Roman Empire and shape future Christian civilization.",
            capabilities: ["Capability for Radical Self-Transformation", "Capability for Theological Synthesis", "Capability for Psychological Self-Analysis"],
            videoUrl: null,
        },
        {
            name: "Ibn Rushd (Averroes)",
            lifespan: "1126-1198 CE",
            title: "The Rational Commentator",
            summary: "An Andalusian philosopher and physician who sought to integrate Aristotelian philosophy with Islamic thought, influencing both Islamic and Western scholasticism.",
            assemblyHistory: "Born in Córdoba into a distinguished family of Islamic judges (qādīs), he was deeply grounded in both Islamic law and the rich Greco-Arabic philosophical tradition of Al-Andalus. His environment was a unique crossroads of Islamic, Jewish, and Christian thought, which he synthesized in his work.",
            broa: "His BROA+ is founded on the harmony of reason and revelation. Beliefs: Philosophy and religion are two paths to the same truth. The natural world operates on rational principles that reveal divine wisdom. Rules: Interpret religious texts at multiple levels (literal for the masses, allegorical for theologians, demonstrative for philosophers). Ontology: An Aristotelian metaphysics of substances and causes, integrated with an emanational cosmology. Authenticity: A life that combines philosophical sophistication with genuine religious commitment and service to the community as a judge and physician.",
            atcf: "He maintained coherence across his multiple roles as philosopher, judge, and physician. Even when he faced persecution and exile for his rationalist views, he maintained his core commitment to the synthesis of philosophy and faith, adapting his communication but not his principles.",
            fop: "He aimed to create a permanent integration of Aristotelian philosophy within Islamic civilization. His comprehensive commentaries on Aristotle were a future-oriented project intended to provide a rational foundation for Islamic thought for generations to come.",
            capabilities: ["Capability for Cross-Cultural Intellectual Synthesis", "Capability for Hierarchical Interpretation", "Capability for Integrating Professional and Philosophical Life"],
            videoUrl: null,
        },
        {
            name: "Thomas Aquinas",
            lifespan: "1225-1274 CE",
            title: "The Theologian Synthesizer",
            summary: "A Dominican friar who created a comprehensive synthesis of Christian theology and Aristotelian philosophy, shaping Western thought for centuries.",
            assemblyHistory: "Born into Italian nobility, he defied his family's wishes by joining the intellectually focused Dominican order. His education under Albert the Great exposed him to the newly rediscovered works of Aristotle, creating the central project of his life: reconciling the systematic rationalism of the Greeks with the revealed truths of Christian faith.",
            broa: "His BROA+ is built on the harmony of faith and reason. Beliefs: Reason and faith both originate from God and cannot truly conflict. Natural reason can understand the created world, while revelation provides truths beyond reason's grasp. Rules: Employ systematic, logical inquiry ('disputed questions') to analyze theological problems, always respecting scriptural authority. Ontology: Reality is a hierarchical order flowing from God, with a distinction between a thing's 'essence' and its 'existence.' Authenticity: An integrated life of rigorous intellectual work and deep contemplative faith, where both serve the Church.",
            atcf: "Aquinas demonstrated remarkable coherence in integrating vast and seemingly contradictory intellectual traditions. His career shows a stable progression from student to master to the author of the monumental Summa Theologica, always maintaining his identity as a faithful scholar serving the Church.",
            fop: "His work was explicitly oriented toward the future of the Church. He created a systematic theological framework and educational method (the Summa) designed to be a permanent resource for training future generations of clergy and theologians, ensuring the Church could engage with the best of secular philosophy.",
            capabilities: ["Capability for Grand Synthesis of Diverse Systems", "Capability for Systematic Theological Argumentation", "Capability for Reconciling Faith and Reason"],
            videoUrl: null,
        },
        {
            name: "Galileo Galilei",
            lifespan: "1564-1642 CE",
            title: "The Experimental Observer",
            summary: "An Italian astronomer, physicist, and engineer whose pioneering use of the telescope and experimental method became a cornerstone of the scientific revolution.",
            assemblyHistory: "His father was a musician and theorist who challenged authority through empirical investigation of sound, providing an early model for Galileo. Living in Renaissance Florence and Padua, he was immersed in a world of artistic innovation and technical craftsmanship, leading him to value direct observation and mathematical precision over traditional scholastic authority.",
            broa: "His BROA+ is grounded in a mathematical and empirical view of nature. Beliefs: The universe is a 'book written in the language of mathematics.' Direct, instrument-aided observation is superior to ancient texts. Rules: Test all theoretical claims with controlled experiments; use technology to extend the senses. Ontology: The cosmos is a unified system governed by universal physical laws, not a hierarchy of separate celestial and terrestrial realms. Authenticity: An unwavering commitment to empirical evidence, even when it conflicts with powerful religious or philosophical authorities.",
            atcf: "Galileo maintained his core identity as a 'mathematical natural philosopher' throughout his life. From his early experiments on motion to his telescopic discoveries and his final, defiant work written under house arrest, he consistently championed the authority of empirical evidence.",
            fop: "He was consciously building a new foundation for science. His Future-Oriented Projections involved establishing an experimental-mathematical method that future investigators could use to progressively unravel the laws of nature, thereby creating a legacy of continuous scientific advancement.",
            capabilities: ["Capability for Empirical Verification", "Capability for Technological Innovation in Science", "Capability for Challenging Dogma with Evidence"],
            videoUrl: null,
        },
        {
            name: "René Descartes",
            lifespan: "1596-1650 CE",
            title: "The Foundational Doubter",
            summary: "A French philosopher, mathematician, and scientist, dubbed the 'father of modern philosophy' for his method of systematic doubt.",
            assemblyHistory: "Educated in the rigorous Jesuit tradition, he became deeply dissatisfied with the lack of certainty in existing philosophy. His experiences in military service and a series of powerful dreams led him to seek a new, indubitable foundation for all knowledge, modeled on the certainty of mathematics.",
            broa: "His BROA+ is built on methodical doubt and rational certainty. Beliefs: Knowledge must be built on foundations that are impossible to doubt ('I think, therefore I am'). The mind (res cogitans) is fundamentally distinct from the body/matter (res extensa). Rules: Accept as true only that which is perceived 'clearly and distinctly.' Break down complex problems into their simplest parts. Ontology: A dualistic universe of mind and matter, with God as the guarantor that our clear ideas correspond to reality. Authenticity: A life of intellectual independence, where truth is discovered through individual reason, not accepted from authority.",
            atcf: "Descartes shows a powerful coherence in his intellectual project. From his early decision to 'raze everything to the ground and begin again from the original foundations,' he systematically executed his philosophical reconstruction over several decades, maintaining his core methodological commitments throughout.",
            fop: "He projected a future where his rational method would unify all human knowledge—from metaphysics to medicine—creating a systematic 'tree of knowledge' that would enable humanity to become 'masters and possessors of nature' for the betterment of all.",
            capabilities: ["Capability for Systematic Doubt", "Capability for Rational Reconstruction of Knowledge", "Capability for Integrating Philosophy and Mathematics"],
            videoUrl: null,
        },
        {
            name: "John Locke",
            lifespan: "1632-1704 CE",
            title: "The Liberal Empiricist",
            summary: "An English philosopher and physician, widely regarded as one of the most influential of Enlightenment thinkers and commonly known as the 'Father of Liberalism.'",
            assemblyHistory: "Shaped by the turmoil of the English Civil War, his Puritan heritage, and his involvement with the emerging scientific revolution (especially through Robert Boyle). His direct experience with political instability and his medical training led him to reject inherited authority in favor of knowledge grounded in experience and observation.",
            broa: "His BROA+ is founded on empiricism and natural rights. Beliefs: All knowledge comes from experience (the mind is a 'tabula rasa'). Individuals possess natural rights to life, liberty, and property. Legitimate government is based on the consent of the governed. Rules: Base beliefs on evidence, not authority. Government must be limited by a constitution and separation of powers. Ontology: The individual is the fundamental moral and political unit. Authenticity: A life of rational independence, where beliefs are formed through individual reason and political participation is a responsibility.",
            atcf: "Locke showed consistency from his early medical and scientific work to his later political philosophy. He consistently applied an empirical, evidence-based method to questions of both knowledge and politics, maintaining his core commitments through political upheaval and exile.",
            fop: "He was designing a blueprint for a stable, free, and prosperous future society. His projections included constitutional democracy, religious tolerance, and a system of education that would prepare citizens for self-governance, all aimed at long-term human progress.",
            capabilities: ["Capability for Grounding Political Theory in Empiricism", "Capability for Designing Constitutional Limits on Power", "Capability for Theorizing Individual Rights"],
            videoUrl: null,
        },
        {
            name: "Immanuel Kant",
            lifespan: "1724-1804 CE",
            title: "The Critical Philosopher",
            summary: "A German philosopher whose comprehensive and systematic work in epistemology, metaphysics, ethics, and aesthetics made him one of the most influential figures in modern Western philosophy.",
            assemblyHistory: "His PRF was formed in the relatively isolated city of Königsberg, shaped by a devout Pietist upbringing (emphasizing inner moral duty) and the rationalist philosophy of Leibniz and Wolff. The skeptical challenge of David Hume awakened him from his 'dogmatic slumber,' forcing him to undertake a 'Copican Revolution' in philosophy.",
            broa: "His BROA+ is the foundation of his Critical Philosophy. Beliefs: We can only know the world as it appears to us (phenomena), structured by the mind's own categories. Moral law is derived from pure reason itself. Rules: The Categorical Imperative—act only according to principles you could will to be universal laws, and always treat humanity as an end, never merely as a means. Ontology: A dual view of reality—the phenomenal world of experience and the noumenal world of things-in-themselves, which allows for both scientific determinism and moral freedom. Authenticity: A life of rational autonomy, where one thinks for oneself and acts according to self-given moral laws.",
            atcf: "Kant's life was one of extraordinary intellectual consistency. After his 'critical turn' around 1770, he spent the rest of his life systematically and coherently building his philosophical system, from the Critique of Pure Reason to his final essays on politics and history.",
            fop: "He projected a future of 'perpetual peace' and a global 'republican' order guided by reason. His entire philosophical system was a future-oriented project aimed at providing a permanent, rational foundation for science, morality, and political progress for all of humanity.",
            capabilities: ["Capability for Systematic Critique of Reason", "Capability for Formulating Universal Moral Principles", "Capability for Synthesizing Rationalism and Empiricism"],
            videoUrl: null,
        },
        {
            name: "Jeremy Bentham",
            lifespan: "1748-1832 CE",
            title: "The Utilitarian Reformer",
            summary: "An English philosopher, jurist, and social reformer regarded as the founder of modern utilitarianism.",
            assemblyHistory: "A child prodigy trained in law, he became deeply disillusioned with the arbitrary and inefficient English legal system. Influenced by Enlightenment thinkers, he sought to replace tradition and 'natural law' with a scientific, rational foundation for law and morality based on empirical human psychology.",
            broa: "His BROA+ is grounded in psychological hedonism and utility maximization. Beliefs: Human beings are governed by two sovereign masters, pain and pleasure. The only rational moral goal is to maximize the total quantity of happiness ('the greatest good for the greatest number'). Rules: The 'Felicific Calculus'—evaluate all actions and policies by systematically calculating their consequences for human happiness. Ontology: A materialist psychology where mind is an emergent property; social institutions are human constructs to be engineered for utility. Authenticity: A life of impartial benevolence guided by systematic rational calculation, free from tradition and sentiment.",
            atcf: "Bentham exhibited remarkable consistency in applying his utilitarian principle to every aspect of society. From his critique of legal fictions to his design for the 'Panopticon' prison and his advocacy for democratic reform, he relentlessly followed his core methodology.",
            fop: "He projected a future where all social institutions—law, government, education, economics—would be rationally designed to maximize public welfare. He founded a movement of 'Philosophical Radicals' to carry this systematic reform project into the future.",
            capabilities: ["Capability for Systematic Social Calculation", "Capability for Institutional Design and Innovation", "Capability for Critiquing Traditional Authority"],
            videoUrl: null,
        },
        {
            name: "John Stuart Mill",
            lifespan: "1806-1873 CE",
            title: "The Liberal Synthesizer",
            summary: "A British philosopher, political economist, and civil servant who was an influential proponent of utilitarianism and liberalism.",
            assemblyHistory: "He was the subject of a rigorous, experimental education by his father, James Mill, designed to create a perfect utilitarian thinker. This intense intellectual training was followed by a 'mental crisis' in his twenties, which led him to integrate Romanticism, emotional development, and the value of individuality into his inherited Benthamite framework. His lifelong intellectual partnership with Harriet Taylor was also fundamental to his development, especially his radical views on gender equality.",
            broa: "His BROA+ represents a qualified utilitarianism. Beliefs: Human happiness includes 'higher' (intellectual, moral) and 'lower' (sensual) pleasures. Individual liberty is essential for personal development and social progress. Rules: The 'Harm Principle'—liberty should only be restricted to prevent harm to others. Encourage 'experiments in living.' Ontology: Individuals and society are interdependent; history is progressive. Authenticity: A life that balances rational analysis with emotional development and serves social improvement.",
            atcf: "Mill's life is a story of coherent synthesis. He successfully integrated the severe rationalism of his upbringing with the Romantic value of individuality, and his philosophical work with his practical engagement as a Member of Parliament, consistently adapting his views based on new insights without losing his core commitment to human progress.",
            fop: "He projected a future of a mature liberal democracy, where educated citizens participate in governance, individual liberty is maximized, and gender equality is achieved. His works like 'On Liberty' and 'The Subjection of Women' were written as guides for this ongoing project of social reform.",
            capabilities: ["Capability for Synthesizing Conflicting Philosophies", "Capability for Championing Individual Liberty", "Capability for Radical Empathy and Gender Equality Advocacy"],
            videoUrl: null,
        },
        {
            name: "Peter Singer",
            lifespan: "1946-Present",
            title: "The Applied Ethicist & Altruist",
            summary: "A contemporary philosopher whose application of utilitarianism to animal rights and global poverty sparked the effective altruism movement.",
            assemblyHistory: "Born in Melbourne to Jewish Austrian parents who escaped the Holocaust, his framework was shaped by a secular upbringing that valued rational inquiry and a deep awareness of the consequences of ethical indifference. His philosophical development at Oxford in the 1960s, a time of social upheaval, solidified his commitment to applying rigorous utilitarian analysis to real-world problems.",
            broa: "His BROA+ is grounded in utilitarian consequentialism. Beliefs: The right action is the one that maximizes welfare for all affected beings. The capacity for suffering (sentience) is the basis for moral consideration. Rules: Impartially maximize welfare; act on evidence of what is most effective; apply principles consistently. Ontology: A naturalistic worldview with a global moral community that includes all sentient beings. Authenticity: A life where one's actions (like charitable giving and lifestyle choices) are consistent with one's stated moral beliefs about reducing suffering.",
            atcf: "Singer has shown remarkable consistency in applying his utilitarian principles across an expanding range of issues, from his groundbreaking work on animal liberation to his arguments on global poverty and effective altruism. He consistently follows the logical conclusions of his framework, even when they are controversial.",
            fop: "He projects a future where the 'moral circle' continues to expand, and where reason and evidence guide our ethical choices. He actively works to build the 'Effective Altruism' movement as an institutional legacy to ensure that future generations can reduce suffering and improve the world more effectively.",
            capabilities: ["Capability for Applied Ethical Innovation", "Capability for Expanding the Moral Circle", "Capability for Public Intellectual Communication", "Capability for Cross-Disciplinary Synthesis"],
            videoUrl: null,
        },
        {
            name: "Derek Parfit",
            lifespan: "1942-2017",
            title: "The Identity Revisionist",
            summary: "A British philosopher who made groundbreaking contributions to personal identity, ethics, and rationality, known for his rigorous use of thought experiments.",
            assemblyHistory: "Shaped by an elite British education (Eton, Oxford) and a deep fascination with puzzles of identity and time. His work was a reaction against what he saw as imprecise thinking in moral philosophy, aiming to bring mathematical rigor to questions of what matters.",
            broa: "His BROA+ is built on a reductionist and impartial view of ethics. Beliefs: Personal identity is not what truly matters; psychological continuity is. There may not be a single 'best' moral theory, but different theories might converge on the same conclusions. Rules: Use thought experiments to test intuitions; strive for logical precision; give equal weight to the well-being of all people, including those in the distant future. Ontology: A naturalistic worldview where complex phenomena like 'the self' reduce to simpler physical and psychological events. Authenticity: An unwavering commitment to intellectual honesty, following arguments wherever they lead, regardless of how counterintuitive the conclusions.",
            atcf: "Parfit's life was one of extreme intellectual coherence. He spent decades meticulously working on his major books, *Reasons and Persons* and *On What Matters*, ensuring every argument was as precise as possible. His identity as a systematic, analytical philosopher never wavered.",
            fop: "He was deeply concerned with the long-term future of humanity. His work on population ethics and future generations was a direct attempt to build a rational framework for making choices that would have the best consequences for all people who will ever live.",
            capabilities: ["Capability for Systematic Philosophical Architecture", "Capability for Thought Experiment Innovation", "Capability for Future-Oriented Moral Focus"],
            videoUrl: null,
        },
        {
            name: "Martha Nussbaum",
            lifespan: "1947-Present",
            title: "The Capabilities Proponent",
            summary: "An American philosopher who champions the 'Capabilities Approach,' arguing that social justice means ensuring every individual has the real opportunity to develop their essential human capabilities.",
            assemblyHistory: "Her framework was formed through a combination of classical philosophy (especially Aristotle), literary studies, and a growing engagement with feminist theory and international development. Her early training as an actor also gave her a deep appreciation for the role of emotions and narrative in moral life.",
            broa: "Her BROA+ is grounded in an Aristotelian and universalist humanism. Beliefs: All humans share a set of central capabilities essential for a flourishing life. Emotions are cognitive and provide vital information for moral reasoning. Rules: Evaluate societies and policies based on whether they provide citizens with the necessary conditions to develop their capabilities. Ontology: A pluralistic view of value; human flourishing is multi-dimensional and cannot be reduced to a single metric like money. Authenticity: An integrated life where intellectual rigor, emotional intelligence, and a commitment to social justice are intertwined.",
            atcf: "Nussbaum has demonstrated remarkable consistency in applying and developing her Capabilities Approach across diverse fields, from ancient Greek ethics to modern constitutional law and international development policy. She coherently integrates philosophical analysis, literary interpretation, and practical policy advocacy.",
            fop: "She projects a future where global justice and national policies are evaluated not by GDP, but by how well they secure a threshold of central capabilities for every single person, creating a more humane and just world.",
            capabilities: ["Capability for Interdisciplinary Synthesis", "Capability for Cross-Cultural Translation", "Capability for Integrating Emotion and Reason"],
            videoUrl: null,
        },
        {
            name: "Kwame Anthony Appiah",
            lifespan: "1954-Present",
            title: "The Rooted Cosmopolitan",
            summary: "A British-Ghanaian philosopher whose work on identity, culture, and cosmopolitanism argues for a world where universal moral concern coexists with respect for particular cultural identities.",
            assemblyHistory: "His unique bicultural upbringing—son of an Asante royal and politician in Ghana and a British aristocrat and author in England—provided him with a direct, lived experience of navigating multiple identities. His education at Cambridge grounded him in the analytical tradition of philosophy, which he then applied to questions of race, culture, and postcolonial identity.",
            broa: "His BROA+ is defined by 'rooted cosmopolitanism.' Beliefs: We have moral obligations to all human beings, but our particular identities and cultural affiliations also have real value. Identity is not an essence but something we choose and construct from available cultural 'scripts.' Rules: Engage in respectful dialogue across cultures; respect individual choices about identity. Ontology: Race is a social construct, not a biological reality, but it has real-world effects. Authenticity: A life that coherently integrates one's multiple cultural affiliations and moral commitments, embracing complexity over purity.",
            atcf: "Appiah's life and work show a consistent effort to bridge divides—between cultures, between academic philosophy and public discourse, and between universal ethics and particular identities. He has maintained a coherent philosophical project while adapting to different institutional and cultural contexts in Ghana, the UK, and the US.",
            fop: "He projects a future of global conversation, where people can learn from different cultural traditions without abandoning their own. His work aims to provide the philosophical tools for a globalized world to manage cultural difference peacefully and productively.",
            capabilities: ["Capability for Cross-Cultural Translation", "Capability for Public Intellectual Integration", "Capability for Deconstructing Essentialist Identities"],
            videoUrl: null,
        }
    ],
    concepts: [
        { 
            name: "Personal Reality Framework (PRF)",
            description: "An agent's unique architecture for organizing experience, comprising their Beliefs, Rules, Ontological commitments, and Authenticity criteria (BROA+). It's a dynamic system, shaped by a person's life story (Assembly History), that filters perception and guides action."
        },
        {
            name: "Capability-Based Coordination & Functional Equivalence",
            description: "The core principle that ethical coordination doesn't require people to share identical beliefs or values. Instead, they can coordinate effectively by developing 'functionally equivalent' capabilities that achieve the same shared goal. Different paths, same ethical function."
        },
        {
            name: "Adaptive Temporal Coherence Function (ATCF)",
            description: "A measure of an agent's ability to maintain identity and integrity over time. It assesses how well one integrates their past experiences, present actions, and future aspirations into a coherent narrative. High ATCF is a mark of ethical maturity and resilience."
        },
        {
            name: "Bootstrap Resolution of Normative Authority",
            description: "The meta-ethical idea that the 'ought' of ethics emerges from the practical necessities of being an agent. Any person who can ask 'Why should I be ethical?' already demonstrates a commitment to the temporal coherence and reasoning that ground ethical coordination. Authority comes from within agency itself."
        },
        {
            name: "Network-Goal Coordination",
            description: "A form of collaboration where diverse stakeholders advance the *same shared network objective* (e.g., 'establish truth and prevent harm') through their different but equivalent skills. This is more resilient than coordination based on temporarily aligned individual interests."
        },
        {
            name: "Cross-Scale Markup Organization",
            description: "The principle that universal information architecture patterns enable coordination across different systems (e.g., biological cells, human consciousness, computer networks). It suggests a deep structural link between logical reasoning and ethical coordination."
        }
    ]
};
